//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaDateAplicatie : DbContext
    {
        public BazaDateAplicatie()
            : base("name=BazaDateAplicatie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calibru> Calibre { get; set; }
        public virtual DbSet<Operatie> Operatii { get; set; }
        public virtual DbSet<Reper> Repere { get; set; }
        public virtual DbSet<Utilizator> Utilizatori { get; set; }
    }
}
