//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;
    using System.Collections.ObjectModel;
    
    
    public partial class Reper : INotifyPropertyChanged
    
    {
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }
    
    
    	private int _id;
    
    
        public int Id { get { return _id; } set { _id = value;  OnPropertyChanged(); } }
    	private string _nume;
    
    
        public string Nume { get { return _nume; } set { _nume = value;  OnPropertyChanged(); } }
    	private long _timpexecutie;
    
    
        public long TimpExecutie { get { return _timpexecutie; } set { _timpexecutie = value;  OnPropertyChanged(); } }
    	private string _tipmaterial;
    
    
        public string TipMaterial { get { return _tipmaterial; } set { _tipmaterial = value;  OnPropertyChanged(); } }
    	private byte[] _desentehnic;
    
    
        public byte[] DesenTehnic { get { return _desentehnic; } set { _desentehnic = value;  OnPropertyChanged(); } }
    	private byte[] _desen3d;
    
    
        public byte[] Desen3d { get { return _desen3d; } set { _desen3d = value;  OnPropertyChanged(); } }
    	private int _pretvanzare;
    
    
        public int PretVanzare { get { return _pretvanzare; } set { _pretvanzare = value;  OnPropertyChanged(); } }
    	private int _costproductie;
    
    
        public int CostProductie { get { return _costproductie; } set { _costproductie = value;  OnPropertyChanged(); } }
    
        public virtual ObservableCollection<Calibru> Calibre { get; set; }
        public virtual ObservableCollection<Operatie> Operatii { get; set; }
    }
}
